apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubrickmiproject-deployment
  labels:
    app: kubrickmiproject
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubrickmiproject
  template:
    metadata:
      labels:
        app: kubrickmiproject
    spec:
      containers:
      - name: kubrickmiproject
        image: kubrickmiproject.azurecr.io/kubrickmiproject:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubrickmiproject-service
spec:
  selector:
    app: kubrickmiproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer